github_user: greenpeace
github_repository: gpes-wells-map
markdown: kramdown
title: "Mapas y gráficos de pozos"
long_title: "Desarollo de los mapas y gráficos de pozos"
css_js_server: "https://storage.googleapis.com/gpes-static/pozos-2019/"
version: "?v=1.0"
lead: >
  <p></p>
